import { mkdirSync } from 'node:fs';
import path from 'node:path';
import { Pool } from 'pg';

export type Value = string | number | null;
/** A bound parameter. Postgres array parameters are sent whole, so `?` may stand for a list. */
export type Param = Value | Value[];
export type Row = Record<string, Value>;
export type QueryResult = { rows: Row[]; changes: number };
export interface Executor {
  query(sql: string, ...values: Param[]): Promise<QueryResult>;
}
export interface Database extends Executor {
  /** `postgres` covers both a TCP connection string and the CloudBase HTTP channel. */
  readonly dialect: 'sqlite' | 'postgres';
  /**
   * Real BEGIN/COMMIT on SQLite and on a TCP Postgres pool. The CloudBase HTTP
   * channel is stateless per statement, so there it just executes the callback —
   * callers must keep multi-statement writes individually idempotent.
   */
  transaction<T>(work: (tx: Executor) => Promise<T>): Promise<T>;
  close(): Promise<void>;
}

const nameExpression = (postgres: boolean) => `COALESCE(${['姓名', '名字', 'name', 'Name'].map(key => `NULLIF(${postgres ? `btrim(fields::json->>'${key}')` : `trim(json_extract(fields, '$.${key}'))`}, '')`).join(', ')}, '')`;

export const schemaStatements = (postgres: boolean): string[] => [
  'CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL)',
  `CREATE TABLE IF NOT EXISTS people (
      id ${postgres ? 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' : 'INTEGER PRIMARY KEY'}, phone TEXT NOT NULL, name TEXT NOT NULL DEFAULT '', fields TEXT NOT NULL,
      token TEXT UNIQUE NOT NULL, created_at TEXT NOT NULL, checked_at TEXT
    )`,
  ...(postgres ? [
    "ALTER TABLE people ADD COLUMN IF NOT EXISTS name TEXT NOT NULL DEFAULT ''",
    `UPDATE people SET name = ${nameExpression(true)} WHERE name = '' AND ${nameExpression(true)} <> ''`,
  ] : []),
  'CREATE UNIQUE INDEX IF NOT EXISTS people_phone_name_idx ON people (phone, name)',
  ...(postgres ? ['ALTER TABLE people DROP CONSTRAINT IF EXISTS people_phone_key'] : []),
  'CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY, expires BIGINT NOT NULL)',
  'CREATE TABLE IF NOT EXISTS drafts (id TEXT PRIMARY KEY, session_hash TEXT NOT NULL, filename TEXT NOT NULL, payload TEXT NOT NULL, expires BIGINT NOT NULL)',
  `CREATE TABLE IF NOT EXISTS imports (id ${postgres ? 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' : 'INTEGER PRIMARY KEY'}, filename TEXT NOT NULL, total INTEGER NOT NULL, added INTEGER NOT NULL, updated INTEGER NOT NULL, created_at TEXT NOT NULL)`,
  'CREATE TABLE IF NOT EXISTS rate_limits (key TEXT PRIMARY KEY, hits INTEGER NOT NULL, expires BIGINT NOT NULL)',
  'CREATE TABLE IF NOT EXISTS uploads (key TEXT PRIMARY KEY, filename TEXT NOT NULL, size INTEGER NOT NULL, expires BIGINT NOT NULL)',
  'CREATE INDEX IF NOT EXISTS people_checked_at_idx ON people (checked_at DESC) WHERE checked_at IS NOT NULL',
  'CREATE INDEX IF NOT EXISTS rate_limits_expires_idx ON rate_limits (expires)',
];

export const schema = (postgres: boolean) => schemaStatements(postgres).map(statement => `${statement};`).join('\n');

export const postgresSql = (sql: string) => { let index = 0; return sql.replace(/\?/g, () => `$${++index}`); };

const EXEC_PGSQL_TIMEOUT_MS = 30000;

export class DatabaseUnavailableError extends Error {
  constructor() { super('服务繁忙，请稍后重试。'); }
}

const isUnavailable = (error: unknown) => {
  const failure = error as { code?: string; message?: string };
  return /^(08|53|57P|57014|ECONN|ETIMEDOUT|EPIPE)/.test(failure.code || '') || /timeout exceeded when trying to connect|Connection terminated|read ECONNRESET/i.test(failure.message || '');
};

/**
 * CloudBase PostgreSQL reached over the environment gateway's `exec-pgsql`
 * endpoint. The managed database exposes no TCP socket to application code, so
 * every statement travels as one HTTP round trip:
 *
 *   POST https://{envId}.api.tcloudbasegateway.com/v1/rdb/exec-pgsql
 *
 * Two consequences shape the callers: the endpoint rejects multi-statement
 * payloads, and it only reports what a statement returns, never a row count.
 * Both are handled here — the schema is applied statement by statement, and
 * `changes` is derived from RETURNING rows, which is why DML in this project
 * always asks for the rows it touched.
 */
export function openCloudBaseDatabase(envId: string, apiKey: string): Database {
  const endpoint = `https://${envId}.api.tcloudbasegateway.com/v1/rdb/exec-pgsql`;
  const max = Number(process.env.DB_HTTP_MAX || 8);
  if (!Number.isSafeInteger(max) || max < 1) throw new Error('DB_HTTP_MAX 必须为正整数。');
  let active = 0;
  const waiting: (() => void)[] = [];
  const acquire = async () => {
    if (active < max) { active++; return; }
    if (waiting.length >= 100) throw new DatabaseUnavailableError();
    await new Promise<void>((resolve, reject) => {
      const ready = () => { clearTimeout(timer); resolve(); };
      const timer = setTimeout(() => {
        waiting.splice(waiting.indexOf(ready), 1);
        reject(new DatabaseUnavailableError());
      }, 5000);
      waiting.push(ready);
    });
  };
  const release = () => { const next = waiting.shift(); if (next) next(); else active--; };
  const call = async (sql: string, values: Param[]): Promise<Row[]> => {
    let response: Response;
    let body: string;
    try {
      response = await fetch(endpoint, {
        method: 'POST',
        headers: { 'content-type': 'application/json', authorization: `Bearer ${apiKey}` },
        body: JSON.stringify({ sql, parameters: values, role: 'cloudbase_postgres' }),
        signal: AbortSignal.timeout(EXEC_PGSQL_TIMEOUT_MS),
      });
      body = await response.text();
    } catch { throw new DatabaseUnavailableError(); }
    if (response.status >= 500 || response.status === 429 || response.status === 408) throw new DatabaseUnavailableError();
    let payload: unknown;
    try { payload = JSON.parse(body); } catch { throw new Error(`数据库返回了无法解析的内容（HTTP ${response.status}）。`); }
    if (!response.ok) {
      const code = payload && typeof payload === 'object' && 'code' in payload ? String(payload.code).replace(/^DATABASE_/, '') : '';
      if (isUnavailable({ code })) throw new DatabaseUnavailableError();
      const detail = payload && typeof payload === 'object' && 'message' in payload ? String((payload as { message: unknown }).message) : '';
      throw new Error(detail || `数据库操作失败（HTTP ${response.status}）。`);
    }
    if (!Array.isArray(payload)) throw new Error('数据库返回格式异常，请稍后重试。');
    return payload as Row[];
  };
  const executor: Executor = {
    async query(sql, ...values) {
      await acquire();
      try {
        const rows = await call(postgresSql(sql), values);
        return { rows, changes: rows.length };
      } finally { release(); }
    },
  };
  return {
    ...executor,
    dialect: 'postgres',
    async transaction(work) { return work(executor); },
    async close() { /* 无长连接可关闭 */ },
  };
}

/** Applies the schema one statement at a time; CloudBase rejects multi-statement payloads. */
export async function migrateCloudBaseDatabase(database: Database): Promise<void> {
  for (const statement of schemaStatements(true)) await database.query(statement);
}

export async function openDatabase(dataDir: string, connectionString = process.env.DATABASE_URL): Promise<Database> {
  const envId = process.env.CLOUDBASE_ENV_ID;
  const apiKey = process.env.CLOUDBASE_API_KEY;
  if (envId && apiKey) {
    const database = openCloudBaseDatabase(envId, apiKey);
    if (process.env.DB_MIGRATE_ON_START !== '0') await migrateCloudBaseDatabase(database);
    return database;
  }
  if (connectionString) {
    const max = Number(process.env.DB_POOL_MAX || 3);
    if (!Number.isSafeInteger(max) || max < 1) throw new Error('DB_POOL_MAX 必须为正整数。');
    const pool = new Pool({ connectionString, max, idleTimeoutMillis: 10000, connectionTimeoutMillis: 5000, statement_timeout: 15000 });
    pool.on('error', error => console.error('数据库空闲连接断开', (error as { code?: string }).code || error.name));
    const executor = (client: Pick<Pool, 'query'>): Executor => ({
      async query(sql, ...values) {
        if (client === pool && pool.waitingCount >= 100) throw new DatabaseUnavailableError();
        try {
          const result = await client.query(postgresSql(sql), values as Value[]);
          return { rows: result.rows, changes: result.rowCount || 0 };
        } catch (error) { if (isUnavailable(error)) throw new DatabaseUnavailableError(); throw error; }
      },
    });
    // Cold starts may initialise simultaneously. Serialize DDL across instances.
    try {
      if (process.env.DB_MIGRATE_ON_START !== '0') {
        const client = await pool.connect();
        try {
          await client.query('BEGIN');
          await client.query('SELECT pg_advisory_xact_lock(731942018)');
          await client.query(schema(true));
          await client.query('COMMIT');
        } catch (error) { await client.query('ROLLBACK'); throw error; }
        finally { client.release(); }
      }
    } catch (error) { await pool.end(); throw error; }
    return {
      ...executor(pool),
      dialect: 'postgres',
      async transaction(work) {
        const client = await pool.connect();
        try {
          await client.query('BEGIN');
          const value = await work(executor(client));
          await client.query('COMMIT');
          return value;
        } catch (error) { await client.query('ROLLBACK'); throw error; }
        finally { client.release(); }
      },
      close: () => pool.end(),
    };
  }
  const { DatabaseSync } = await import('node:sqlite');
  mkdirSync(dataDir, { recursive: true, mode: 0o700 });
  const sqlite = new DatabaseSync(path.join(dataDir, 'checkin.sqlite'));
  sqlite.exec('PRAGMA journal_mode = WAL; BEGIN IMMEDIATE');
  try {
    const columns = sqlite.prepare('PRAGMA table_info(people)').all();
    if (columns.length && !columns.some(column => column.name === 'name')) {
      sqlite.exec(`ALTER TABLE people RENAME TO people_phone_unique;
        ${schemaStatements(false)[1]};
        INSERT INTO people (id, phone, name, fields, token, created_at, checked_at)
          SELECT id, phone, ${nameExpression(false)}, fields, token, created_at, checked_at FROM people_phone_unique;
        DROP TABLE people_phone_unique;`);
    }
    sqlite.exec(schema(false) + '; COMMIT');
  } catch (error) { sqlite.exec('ROLLBACK'); sqlite.close(); throw error; }
  const executor: Executor = {
    async query(sql, ...values) {
      const statement = sqlite.prepare(sql);
      const bound = values as Value[];
      // A statement with a result shape is a SELECT or a DML using RETURNING;
      // both report their affected rows as the row list.
      if (statement.columns().length) {
        const rows = statement.all(...bound) as Row[];
        return { rows, changes: rows.length };
      }
      return { rows: [], changes: Number(statement.run(...bound).changes) };
    },
  };
  // Async handlers must not interleave another request inside a SQLite transaction.
  let pending = Promise.resolve();
  const locked = <T>(work: () => Promise<T>) => {
    const result = pending.then(work);
    pending = result.then(() => {}, () => {});
    return result;
  };
  return {
    dialect: 'sqlite',
    query: (sql, ...values) => locked(() => executor.query(sql, ...values)),
    transaction: work => locked(async () => {
      sqlite.exec('BEGIN IMMEDIATE');
      try { const value = await work(executor); sqlite.exec('COMMIT'); return value; }
      catch (error) { sqlite.exec('ROLLBACK'); throw error; }
    }),
    close: () => locked(async () => { sqlite.close(); }),
  };
}
